### PR TITLE
Added support django 1.3

### PR DESCRIPTION
**Pull request by saippuakauppias**

### CODE REVIEW

**Comment by kennethreitz** [comment]
wow, this really complicates things.

**Comment by kennethreitz** [comment]
I think I'm going to hold off on this for now. Thanks for the contribution though :)

**Comment by skeet70** [comment]
+1 on adding this. Thanks @saippuakauppias!

**Comment by kennethreitz** [comment]
If anyone can test this out in production and attest that it's working well, I'd be happy to reconsider!

**Comment by saippuakauppias** [comment]
I'm tested this in production, but decline this package when I get some errors in celery (https://github.com/kennethreitz/django-postgrespool/issues/3) :(

**Comment by skeet70** [comment]
Pushing to production. We also have celery tasks, but they're intermittent and non-critical, so I can provide production info on both this issues if we run into anything.

**Comment by skeet70** [comment]
This appears to be working fine for us in production. We're getting DB out of memory errors once every five hours, but that may be unrelated. The could not fork connection errors we were getting are gone.

**Pull request closed without merging**
